version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: appgr8-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: appgr8-db
      POSTGRES_USER: appgr8
      POSTGRES_PASSWORD: appgr8
    volumes:
      - appgr8-db:/var/lib/postgresql/data
    networks:
      - appgr8-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: default@appgr8.com
      PGADMIN_DEFAULT_PASSWORD: appgr8
    ports:
      - 5050:80
    volumes:
      - appgr8-pg:/var/lib/pgadmin
    networks:
      - appgr8-network
networks:
  appgr8-network:
    name: appgr8-network
    driver: bridge
volumes:
  appgr8-db:
    name: appgr8-db
  appgr8-pg:
    name: appgr8-pg